### ISSUE TITLE
collecting the data form count-views.yaml file

### ISSUE THREAD

**Issue by erdinctogulga** [Perlkonig/grav-plugin-count-views#4]
is there anyway to collect that data from count-views.yaml? 
ext. get pages by popularity for 50+ views of pages??

**Comment by Perlkonig** [comment]
Yup. [I do that in my Knowledge Base theme.](https://github.com/Perlkonig/grav-theme-knowledge-base/blob/master/templates/partials/sidebar.html.twig#L38-L66)

Though I see that I need to update that to use the `vewcounts` variable instead of `config.plugins`. I'll do that next release. Let me know if you still have issues!

**Comment by erdinctogulga** [comment]
thanks a lot 👍
