### ISSUE TITLE
Count 0

### ISSUE THREAD

**Issue by Alexgithub2016** [Perlkonig/grav-plugin-count-views#5]
Hi
I use count view in grav  but only 0 view in each page

**Comment by mrsarge** [comment]
I just had the same issue calling ```{{ viewcounts }}``` in my twig file. I'll leave some infos here since I had a hard time to figure it out.

It's an associative array, so you need to call ```{{ viewcounts.key }}``` and not just {{ viewcounts }} which will return 0.

The plugin use the ```page.route``` system variable as a key, so, you can use ```{{ viewcounts[page.route] }}``` to get the current page variable.

Also, since the ```page.route``` system variable contains the '/' preceding the current page folder name, you can't use ```{{ viewcounts./page-folder-name }}``` to get a specific page view counts.

You need to use ```{{ viewcounts['/page-folder-name'] }}```

Hope it can help others!

**Comment by Perlkonig** [comment]
@Alexgithub2016 I'm so sorry this issue got missed! I'm usually really good about getting to them. Can you post the code you're using?

@mrsarge The docs do say it's an associative array, but I will add a concrete example for clarity. And yes, the bare slash, like the bare hyphen, can't be used. It must be quoted.

**Comment by Perlkonig** [comment]
Just added two concrete examples. The demo link is also at the top of the page.

**Comment by mrsarge** [comment]
I know the doc said it was an associative array, I just didn't know how to access it and couldn't find it in the Grav docs. I figured I wouldn't be the only one to search for this information and then saw this unresolved issue.

Thank you for this plugin and for the quick update of the doc.
